# Generated by Django 4.2.6 on 2023-10-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="restaurant.category",
            ),
        ),
    ]
