# Generated by Django 4.2.6 on 2023-10-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_menu_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_of_the_day",
            field=models.BooleanField(default=False),
        ),
    ]
