# Generated by Django 4.2.6 on 2023-10-28 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonDRF", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="inventroy",
            new_name="inventory",
        ),
    ]
